FreestoneBlogBundle_homepage:
  pattern:  /
  defaults: { _controller: FreestoneBlogBundle:Page:index }
  requirements:
    _method:  GET
    
FreestoneBlogBundle_about:
  pattern:  /about
  defaults: { _controller: FreestoneBlogBundle:Page:about }
  requirements:
      _method: GET
      
FreestoneBlogBundle_contact:
  pattern:  /contact
  defaults: { _controller: FreestoneBlogBundle:Page:contact }
  requirements:
      _method: GET|POST
      
FreestoneBlogBundle_blog_show:
  pattern: /{id}
  defaults: { _controller: FreestoneBlogBundle:Blog:show }
  requirements:
    _method: GET
    id: \d+