parameters:
#    freestone_blog.example.class: Freestone\BlogBundle\Example

services:
#    freestone_blog.example:
#        class: %freestone_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
